[package]
name = "nov-05"
version = "0.1.0"
authors = ["lineville <lin01@quantumscape.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
