#!/bin/bash

now=$(date +%b-%d | tr '[:upper:]' '[:lower:]')
echo "Creating Rust Project for $now"
cargo new "$now"

cd "$now" || exit
echo "Building Project"
cargo build
echo "Opening in VS Code"
code .
