#!/bin/zsh

templateRepo=https://github.com/lineville/TypeScript-Mocha-Template

echo "Gloning template project from: $templateRepo"

git clone $templateRepo

now=$(date +%b-%d | tr '[:upper:]' '[:lower:]')

echo "Renaming template to $now"
mv TypeScript-Mocha-Template $now

cd $now
echo 'Installing dependencies ...'
npm i
code .
npm t
