[package]
name = "oct-27"
version = "0.1.0"
authors = ["liamneville"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
